version: '3.4'

services:
  farmaatte-api:
    image: farmaatte-api
    build:
      context: . 
      dockerfile: ./Dockerfile
    container_name: farmaatte-api
    ports:
      - 2097:2097
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
networks:
  farmaatte-net:
    name: farmaatte-net
    external: true